# Generated by Django 4.1 on 2022-11-01 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'public"."usuario',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('titulo', models.CharField(max_length=250)),
                ('assuntos', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Aulas',
                'db_table': 'public"."aula',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Avisos',
                'db_table': 'public"."aviso',
            },
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turma_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bibliografias',
                'db_table': 'public"."bibliografia',
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turma_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cronogromas',
                'db_table': 'public"."cronograma',
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('resolvida', models.BooleanField()),
                ('publicada', models.BooleanField()),
                ('labels', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Duvidas',
                'db_table': 'public"."duvida',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'db_table': 'public"."turma',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTurma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('expulso', models.BooleanField()),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuario Turmas',
                'db_table': 'public"."usuario_turma',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
            options={
                'verbose_name_plural': 'Topicos',
                'db_table': 'public"."topico',
            },
        ),
        migrations.CreateModel(
            name='RespostaDuvida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=700)),
                ('duvida_id', models.ForeignKey(db_column='duvida_id', on_delete=django.db.models.deletion.CASCADE, to='api.duvida')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resposta Duvidas',
                'db_table': 'public"."resposta_duvida',
            },
        ),
        migrations.CreateModel(
            name='RespostaAtividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField()),
                ('data_envio', models.DateField()),
                ('envio_confirmado', models.BooleanField()),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('aula_id', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, to='api.aula')),
                ('topico_id', models.ForeignKey(db_column='topico_id', on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'db_table': 'public"."material',
            },
        ),
        migrations.AddField(
            model_name='duvida',
            name='turma_id',
            field=models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma'),
        ),
        migrations.CreateModel(
            name='ComentarioAviso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=700)),
                ('aviso_id', models.ForeignKey(db_column='aviso_id', on_delete=django.db.models.deletion.CASCADE, to='api.aviso')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentario Avisos',
                'db_table': 'public"."comentario_aviso',
            },
        ),
        migrations.AddField(
            model_name='aviso',
            name='turma_id',
            field=models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='usario_id',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aula',
            name='cronograma_id',
            field=models.ForeignKey(db_column='cronograma_id', on_delete=django.db.models.deletion.CASCADE, to='api.cronograma'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('prazo', models.DateField()),
                ('pontuacao', models.IntegerField()),
                ('topico_id', models.ForeignKey(db_column='topico_id', on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
                'db_table': 'public"."atividade',
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('atividade_id', models.ForeignKey(db_column='atividade_id', on_delete=django.db.models.deletion.CASCADE, to='api.atividade')),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('resposta_atividade_id', models.ForeignKey(db_column='resposta_atividade_id', on_delete=django.db.models.deletion.CASCADE, to='api.respostaatividade')),
            ],
            options={
                'verbose_name_plural': 'Anexos',
                'db_table': 'public"."anexos',
            },
        ),
    ]
