# Generated by Django 4.1 on 2022-10-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turma_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cronogromas',
                'db_table': 'public"."cronograma',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('titulo', models.CharField(max_length=250)),
                ('assuntos', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=700)),
                ('cronograma_id', models.ForeignKey(db_column='cronograma_id', on_delete=django.db.models.deletion.CASCADE, to='api.cronograma')),
            ],
            options={
                'verbose_name_plural': 'Aulas',
                'db_table': 'public"."aula',
            },
        ),
    ]
