# Generated by Django 4.1 on 2022-10-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turma_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bibliografias',
                'db_table': 'public"."bibliografia',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'db_table': 'public"."turma',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'public"."usuario',
            },
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='turma_id',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='UsuarioTurma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('expulso', models.BooleanField()),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'verbose_name_plural': 'Usuario Turmas',
                'db_table': 'public"."usuario_turma',
            },
        ),
    ]
