# Generated by Django 4.1 on 2022-10-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bibliografia_turma_usuario_alter_cronograma_turma_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
                ('usario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'verbose_name_plural': 'Avisos',
                'db_table': 'public"."aviso',
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('resolvida', models.BooleanField()),
                ('publicada', models.BooleanField()),
                ('labels', models.CharField(max_length=250)),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
            options={
                'verbose_name_plural': 'Duvidas',
                'db_table': 'public"."duvida',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
            options={
                'verbose_name_plural': 'Topicos',
                'db_table': 'public"."topico',
            },
        ),
        migrations.CreateModel(
            name='RespostaDuvida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=700)),
                ('duvida_id', models.ForeignKey(db_column='duvida_id', on_delete=django.db.models.deletion.CASCADE, to='api.duvida')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'verbose_name_plural': 'Resposta Duvidas',
                'db_table': 'public"."resposta_duvida',
            },
        ),
        migrations.CreateModel(
            name='RespostaAtividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField()),
                ('data_envio', models.DateField()),
                ('envio_confirmado', models.BooleanField()),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('aula_id', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, to='api.aula')),
                ('topico_id', models.ForeignKey(db_column='topico_id', on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'db_table': 'public"."material',
            },
        ),
        migrations.CreateModel(
            name='ComentarioAviso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=700)),
                ('aviso_id', models.ForeignKey(db_column='aviso_id', on_delete=django.db.models.deletion.CASCADE, to='api.aviso')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'verbose_name_plural': 'Comentario Avisos',
                'db_table': 'public"."comentario_aviso',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=700)),
                ('prazo', models.DateField()),
                ('pontuacao', models.IntegerField()),
                ('topico_id', models.ForeignKey(db_column='topico_id', on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
                ('turma_id', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
                'db_table': 'public"."atividade',
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('atividade_id', models.ForeignKey(db_column='atividade_id', on_delete=django.db.models.deletion.CASCADE, to='api.atividade')),
                ('material_id', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('resposta_atividade_id', models.ForeignKey(db_column='resposta_atividade_id', on_delete=django.db.models.deletion.CASCADE, to='api.respostaatividade')),
            ],
            options={
                'verbose_name_plural': 'Anexos',
                'db_table': 'public"."anexos',
            },
        ),
    ]
