# Generated by Django 4.1 on 2022-11-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_turma_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='usario_id',
            new_name='usuario_id',
        ),
    ]
