# Generated by Django 4.1 on 2022-11-08 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_turma_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="professor_id",
            field=models.ForeignKey(
                db_column="professor_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
