# Generated by Django 4.1 on 2022-11-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_usario_id_aviso_usuario_id'),
        ('api', '0003_turma_professor_id'),
    ]

    operations = [
    ]
