# Generated by Django 4.1 on 2022-10-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_usuario_senha_usuario_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="codigo",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
